name: Enable automerge on dependabot PRs

on:
  pull_request_target:

jobs:
  automerge:
    name: Enable automerge on dependabot PRs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - run: gh pr merge ${{ github.event.pull_request.html_url }} --auto --squash
      - run: gh pr review ${{ github.event.pull_request.html_url }} --approve
    env:
      GH_TOKEN: ${{ github.token }}
